import type { Student, Lecturer, SystemUser } from '@/types';

export const SEED_STUDENTS: Student[] = [
  {
    id: '1',
    name: "Kabir Rabi'atu",
    email: 'kabir.rabi@ksitm.edu',
    phone: '09030074007',
    program: 'COM',
    level: '200',
    gpa: 3.8,
    attendance: 92,
    status: 'active',
  },
  {
    id: '2',
    name: 'Faruk Aisha Sambo',
    email: 'faruk.aisha@ksitm.edu',
    phone: '08133554894',
    program: 'COM',
    level: '200',
    gpa: 3.6,
    attendance: 88,
    status: 'active',
  },
  {
    id: '3',
    name: 'Sani Khadija',
    email: 'sani.khadija@ksitm.edu',
    phone: '09010925004',
    program: 'COM',
    level: '200',
    gpa: 3.2,
    attendance: 75,
    status: 'warning',
  },
  {
    id: '4',
    name: 'Mustapha Fatima',
    email: 'mustapha.fatima@ksitm.edu',
    phone: '07049545010',
    program: 'COM',
    level: '200',
    gpa: 3.9,
    attendance: 95,
    status: 'active',
  },
];

export const SEED_LECTURERS: Lecturer[] = [
  {
    id: '1',
    name: 'Dr. Abubakar Ahmad',
    email: 'abubakar@ksitm.edu.ng',
    department: 'COM',
    courses: 4,
    avgScore: 72,
    rating: 4.5,
    passRate: 82,
    status: 'active',
  },
  {
    id: '2',
    name: 'Lawal Ahmad Al-Hassan',
    email: 'lawal.ahmad@ksitm.edu.ng',
    department: 'COM',
    courses: 3,
    avgScore: 68,
    rating: 4.2,
    passRate: 76,
    status: 'active',
  },
  {
    id: '3',
    name: 'Aisha Abdulkadiri',
    email: 'aisha.abdulkadiri@ksitm.edu.ng',
    department: 'COM',
    courses: 3,
    avgScore: 75,
    rating: 4.7,
    passRate: 88,
    status: 'active',
  },
  {
    id: '4',
    name: 'Mohammed Hamza Kankara',
    email: 'mohammed.hamza@ksitm.edu.ng',
    department: 'COM',
    courses: 2,
    avgScore: 60,
    rating: 3.8,
    passRate: 68,
    status: 'active',
  },
  {
    id: '5',
    name: 'Abdullahi Hassan Dan Ali',
    email: 'abdullahi.hassan@ksitm.edu.ng',
    department: 'COM',
    courses: 3,
    avgScore: 65,
    rating: 4.0,
    passRate: 72,
    status: 'active',
  },
];

export const SEED_USERS: SystemUser[] = [
  {
    id: '1',
    name: "Kabir Rabi'atu",
    email: 'kabir.rabi@ksitm.edu.ng',
    role: 'student',
    department: 'COM',
    status: 'active',
    lastLogin: '2024-01-15',
    permissions: ['student', 'view_grades'],
  },
  {
    id: '2',
    name: 'Dr. Abubakar Ahmad',
    email: 'abubakar@ksitm.edu.ng',
    role: 'lecturer',
    department: 'COM',
    status: 'active',
    lastLogin: '2024-01-15',
    permissions: ['lecturer', 'attendance', 'grading'],
  },
  {
    id: '3',
    name: 'Prof. Fatima Abubakar',
    email: 'fatima@ksitm.edu.ng',
    role: 'hod',
    department: 'COM',
    status: 'active',
    lastLogin: '2024-01-14',
    permissions: ['hod', 'department_management', 'reports'],
  },
  {
    id: '4',
    name: 'Alhaji Sani Bello',
    email: 'sani@ksitm.edu.ng',
    role: 'admin',
    status: 'active',
    lastLogin: '2024-01-15',
    permissions: ['admin', 'institution_management'],
  },
  {
    id: '5',
    name: 'Kauthar Kabir',
    email: 'kauthar@ksitm.edu.ng',
    role: 'sysadmin',
    status: 'active',
    lastLogin: '2024-01-15',
    permissions: ['sysadmin', 'system_management'],
  },
  {
    id: '6',
    name: 'Faruk Aisha Sambo',
    email: 'faruk.aisha@ksitm.edu.ng',
    role: 'student',
    department: 'COM',
    status: 'inactive',
    lastLogin: '2024-01-10',
    permissions: ['student', 'view_grades'],
  },
];
